=== Assayyaad/CV/data/schemas/certificates.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "certificates.schema.json",

  "title": "Certificates",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "description": "Name of the certificate"
      },
      "id": {
        "type": "string",
        "description": "Certificate ID"
      },
      "image": {
        "type": "string",
        "description": "Image URL or path"
      },
      "link": {
        "type": "string",
        "format": "uri",
        "description": "Link to the certificate"
      },
      "provider": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Name of the provider"
          },
          "link": {
            "type": "string",
            "format": "uri",
            "description": "Link to the provider"
          },
          "icon": {
            "type": "string",
            "description": "Icon identifier or class"
          }
        },
        "required": ["name", "link", "icon"],
        "additionalProperties": false,
        "description": "Certificate provider information"
      }
    },
    "required": ["name", "id", "image", "link", "provider"],
    "additionalProperties": false
  }
}

=== Assayyaad/CV/data/pages/game-programmer/certificates.json
[
  {
    "name": "JavaScript Algorithms and Data Structures",
    "id": "",
    "image": "/assets/cert/javascript-algorithms-and-data-structures.png",
    "link": "https://freecodecamp.org/certification/Assayyaad/javascript-algorithms-and-data-structures",
    "provider": {
      "name": "FreeCodeCamp",
      "link": "https://freecodecamp.org",
      "icon": "simple-icons:freecodecamp"
    }
  },
  {
    "name": "Introduction to C#",
    "id": "CC-KQMDTAMA",
    "image": "/assets/cert/introduction-to-csharp.png",
    "link": "https://www.sololearn.com/en/certificates/CC-KQMDTAMA",
    "provider": {
      "name": "Sololearn",
      "link": "https://sololearn.com",
      "icon": "simple-icons:sololearn"
    }
  },
  {
    "name": "Introduction to JavaScript",
    "id": "CC-7A1QGUWT",
    "image": "/assets/cert/introduction-to-javascript.png",
    "link": "https://www.sololearn.com/en/certificates/CC-7A1QGUWT",
    "provider": {
      "name": "Sololearn",
      "link": "https://sololearn.com",
      "icon": "simple-icons:sololearn"
    }
  },
  {
    "name": "C++",
    "id": "CT-DKF29HTQ",
    "image": "/assets/cert/cplusplus.png",
    "link": "https://www.sololearn.com/en/certificates/CT-DKF29HTQ",
    "provider": {
      "name": "Sololearn",
      "link": "https://sololearn.com",
      "icon": "simple-icons:sololearn"
    }
  },
  {
    "name": "Tech for Everyone",
    "id": "CC-49YAACNH",
    "image": "/assets/cert/tech-for-everyone.png",
    "link": "https://api2.sololearn.com/v2/certificates/CC-49YAACNH/image/png",
    "provider": {
      "name": "Sololearn",
      "link": "https://sololearn.com",
      "icon": "simple-icons:sololearn"
    }
  }
]
